version: "3.8"
volumes:
  postgres_volume:

services:
  pg-edication-bot-db:
    image: postgres:14-alpine3.15
    container_name: "pg-post-test-db"
    environment:
      - POSTGRES_DB=post-test-db
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 54324:5432
